//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""GameActionMap"",
            ""id"": ""3c7491ce-9deb-43f0-9330-dbcc2148773d"",
            ""actions"": [
                {
                    ""name"": ""MouseMoveHorizontal"",
                    ""type"": ""Button"",
                    ""id"": ""337519c2-3823-4114-a388-eaf1fa842eaa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseMoveVertical"",
                    ""type"": ""Button"",
                    ""id"": ""7b960ede-484b-44b1-85f7-89ffaaec1ca7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseMove"",
                    ""type"": ""Value"",
                    ""id"": ""a7ae69dc-a5e5-4ea9-bff3-cc788118d675"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftMouseButton"",
                    ""type"": ""Button"",
                    ""id"": ""1ba237b6-39fa-48f9-a038-a5655de0b54a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleMouseButton"",
                    ""type"": ""Button"",
                    ""id"": ""343f8960-133b-4a29-84b1-10708c733eba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightMouseButton"",
                    ""type"": ""Button"",
                    ""id"": ""ddab8beb-48e5-4223-adff-3e71d3e10c4f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraZoom"",
                    ""type"": ""Value"",
                    ""id"": ""cd33c710-4e56-47a2-82eb-b81fe397cdc0"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""AD"",
                    ""id"": ""3903a01b-4863-4a67-bac8-4b30299dc4da"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMoveHorizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""3fd949c6-b06f-4e17-8ab6-0562e03094b8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMoveHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9ada1a50-01cc-451a-be7a-8a70d11a081f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMoveHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WS"",
                    ""id"": ""a9f3e675-9d7a-4eb5-a596-6ddc5afff67f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMoveHorizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0d2246c4-239e-43bb-9a5b-b58f8f2b8069"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMoveHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b8959b9e-773c-44b3-a754-2b9b9ad2261d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMoveHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8147153e-3f6d-4a4c-8417-3d950ff60f1f"",
                    ""path"": ""<Mouse>/position/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3508046d-ec57-42dc-b999-a33a8daed2b5"",
                    ""path"": ""<Mouse>/position/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfb9bafd-5f09-4803-847f-293bee5a0095"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e941b1ed-e7e8-4d8f-990e-2a9fdc2e4e7c"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiddleMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0d879a9-2a48-49d7-aaa3-d5213bb82008"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightMouseButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""143f5acf-9e6e-4ba7-9341-48760e452f61"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""3627fe12-e917-4213-aca1-609357a38687"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""69942a98-7c72-4c05-9c14-19943929bec3"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""AD"",
                    ""id"": ""560c59eb-032d-4fd6-8178-4747236f300a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMoveVertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a946c809-9d7a-43f8-b8d2-71db0e5d25ee"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMoveVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""abebe3bd-a451-44c0-a631-fdd17bfc6cf9"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMoveVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WS"",
                    ""id"": ""5f8354a4-32ec-4d5c-aa4c-34d7586281d7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMoveVertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""57cebf6c-d8da-4080-8ced-b594b0954c13"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMoveVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""3968cc0d-4fea-45ed-9fef-4bf83c66f5f1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseMoveVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameActionMap
        m_GameActionMap = asset.FindActionMap("GameActionMap", throwIfNotFound: true);
        m_GameActionMap_MouseMoveHorizontal = m_GameActionMap.FindAction("MouseMoveHorizontal", throwIfNotFound: true);
        m_GameActionMap_MouseMoveVertical = m_GameActionMap.FindAction("MouseMoveVertical", throwIfNotFound: true);
        m_GameActionMap_MouseMove = m_GameActionMap.FindAction("MouseMove", throwIfNotFound: true);
        m_GameActionMap_LeftMouseButton = m_GameActionMap.FindAction("LeftMouseButton", throwIfNotFound: true);
        m_GameActionMap_MiddleMouseButton = m_GameActionMap.FindAction("MiddleMouseButton", throwIfNotFound: true);
        m_GameActionMap_RightMouseButton = m_GameActionMap.FindAction("RightMouseButton", throwIfNotFound: true);
        m_GameActionMap_CameraZoom = m_GameActionMap.FindAction("CameraZoom", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameActionMap
    private readonly InputActionMap m_GameActionMap;
    private List<IGameActionMapActions> m_GameActionMapActionsCallbackInterfaces = new List<IGameActionMapActions>();
    private readonly InputAction m_GameActionMap_MouseMoveHorizontal;
    private readonly InputAction m_GameActionMap_MouseMoveVertical;
    private readonly InputAction m_GameActionMap_MouseMove;
    private readonly InputAction m_GameActionMap_LeftMouseButton;
    private readonly InputAction m_GameActionMap_MiddleMouseButton;
    private readonly InputAction m_GameActionMap_RightMouseButton;
    private readonly InputAction m_GameActionMap_CameraZoom;
    public struct GameActionMapActions
    {
        private @InputActions m_Wrapper;
        public GameActionMapActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseMoveHorizontal => m_Wrapper.m_GameActionMap_MouseMoveHorizontal;
        public InputAction @MouseMoveVertical => m_Wrapper.m_GameActionMap_MouseMoveVertical;
        public InputAction @MouseMove => m_Wrapper.m_GameActionMap_MouseMove;
        public InputAction @LeftMouseButton => m_Wrapper.m_GameActionMap_LeftMouseButton;
        public InputAction @MiddleMouseButton => m_Wrapper.m_GameActionMap_MiddleMouseButton;
        public InputAction @RightMouseButton => m_Wrapper.m_GameActionMap_RightMouseButton;
        public InputAction @CameraZoom => m_Wrapper.m_GameActionMap_CameraZoom;
        public InputActionMap Get() { return m_Wrapper.m_GameActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameActionMapActions set) { return set.Get(); }
        public void AddCallbacks(IGameActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_GameActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameActionMapActionsCallbackInterfaces.Add(instance);
            @MouseMoveHorizontal.started += instance.OnMouseMoveHorizontal;
            @MouseMoveHorizontal.performed += instance.OnMouseMoveHorizontal;
            @MouseMoveHorizontal.canceled += instance.OnMouseMoveHorizontal;
            @MouseMoveVertical.started += instance.OnMouseMoveVertical;
            @MouseMoveVertical.performed += instance.OnMouseMoveVertical;
            @MouseMoveVertical.canceled += instance.OnMouseMoveVertical;
            @MouseMove.started += instance.OnMouseMove;
            @MouseMove.performed += instance.OnMouseMove;
            @MouseMove.canceled += instance.OnMouseMove;
            @LeftMouseButton.started += instance.OnLeftMouseButton;
            @LeftMouseButton.performed += instance.OnLeftMouseButton;
            @LeftMouseButton.canceled += instance.OnLeftMouseButton;
            @MiddleMouseButton.started += instance.OnMiddleMouseButton;
            @MiddleMouseButton.performed += instance.OnMiddleMouseButton;
            @MiddleMouseButton.canceled += instance.OnMiddleMouseButton;
            @RightMouseButton.started += instance.OnRightMouseButton;
            @RightMouseButton.performed += instance.OnRightMouseButton;
            @RightMouseButton.canceled += instance.OnRightMouseButton;
            @CameraZoom.started += instance.OnCameraZoom;
            @CameraZoom.performed += instance.OnCameraZoom;
            @CameraZoom.canceled += instance.OnCameraZoom;
        }

        private void UnregisterCallbacks(IGameActionMapActions instance)
        {
            @MouseMoveHorizontal.started -= instance.OnMouseMoveHorizontal;
            @MouseMoveHorizontal.performed -= instance.OnMouseMoveHorizontal;
            @MouseMoveHorizontal.canceled -= instance.OnMouseMoveHorizontal;
            @MouseMoveVertical.started -= instance.OnMouseMoveVertical;
            @MouseMoveVertical.performed -= instance.OnMouseMoveVertical;
            @MouseMoveVertical.canceled -= instance.OnMouseMoveVertical;
            @MouseMove.started -= instance.OnMouseMove;
            @MouseMove.performed -= instance.OnMouseMove;
            @MouseMove.canceled -= instance.OnMouseMove;
            @LeftMouseButton.started -= instance.OnLeftMouseButton;
            @LeftMouseButton.performed -= instance.OnLeftMouseButton;
            @LeftMouseButton.canceled -= instance.OnLeftMouseButton;
            @MiddleMouseButton.started -= instance.OnMiddleMouseButton;
            @MiddleMouseButton.performed -= instance.OnMiddleMouseButton;
            @MiddleMouseButton.canceled -= instance.OnMiddleMouseButton;
            @RightMouseButton.started -= instance.OnRightMouseButton;
            @RightMouseButton.performed -= instance.OnRightMouseButton;
            @RightMouseButton.canceled -= instance.OnRightMouseButton;
            @CameraZoom.started -= instance.OnCameraZoom;
            @CameraZoom.performed -= instance.OnCameraZoom;
            @CameraZoom.canceled -= instance.OnCameraZoom;
        }

        public void RemoveCallbacks(IGameActionMapActions instance)
        {
            if (m_Wrapper.m_GameActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_GameActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameActionMapActions @GameActionMap => new GameActionMapActions(this);
    public interface IGameActionMapActions
    {
        void OnMouseMoveHorizontal(InputAction.CallbackContext context);
        void OnMouseMoveVertical(InputAction.CallbackContext context);
        void OnMouseMove(InputAction.CallbackContext context);
        void OnLeftMouseButton(InputAction.CallbackContext context);
        void OnMiddleMouseButton(InputAction.CallbackContext context);
        void OnRightMouseButton(InputAction.CallbackContext context);
        void OnCameraZoom(InputAction.CallbackContext context);
    }
}
